# Generated by Django 5.0.3 on 2024-03-16 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_pln', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.CharField(max_length=255)),
                ('serial_numbers', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_location', models.CharField(max_length=255)),
                ('auctions', models.ManyToManyField(related_name='auctionsets', to='sell_that_sheet.auction')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_location', models.CharField(max_length=255)),
                ('photos', models.ManyToManyField(related_name='photosets', to='sell_that_sheet.photo')),
                ('thumbnail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_photoset', to='sell_that_sheet.photo')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='photoset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell_that_sheet.photoset'),
        ),
    ]
