# Generated by Django 5.0.3 on 2024-03-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_that_sheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allegro_id', models.CharField(max_length=255, verbose_name='Allegro parameter ID')),
                ('name', models.CharField(max_length=255, verbose_name='Parameter name')),
                ('type', models.CharField(max_length=255, verbose_name='Parameter type')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=255, verbose_name='Parameter Value name')),
                ('value_id', models.CharField(max_length=35, verbose_name='Parameter Value id')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell_that_sheet.auction', verbose_name='Associated Auction')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell_that_sheet.parameter', verbose_name='Associated Parameter')),
            ],
        ),
    ]
