# Generated by Django 5.0.3 on 2025-01-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell_that_sheet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="keywordtranslation",
            name="shared_across_categories",
            field=models.BooleanField(default=False),
        ),
    ]
