# Generated by Django 5.0.3 on 2025-01-23 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell_that_sheet", "0002_keywordtranslation_shared_across_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionParameterTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.CharField(max_length=255)),
                (
                    "auction_parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sell_that_sheet.auctionparameter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParameterTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.CharField(max_length=255)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sell_that_sheet.parameter",
                    ),
                ),
            ],
        ),
    ]
