# Generated by Django 5.0.3 on 2024-09-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sell_that_sheet",
            "0004_auction_shipment_price_alter_auction_price_euro_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
