# Generated by Django 5.0.3 on 2024-09-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell_that_sheet", "0006_auction_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllegroToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.JSONField()),
                ("obtained_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
