# Generated by Django 5.0.3 on 2024-09-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell_that_sheet", "0007_allegrotoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllegroAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="AllegroToken",
        ),
    ]
