# Generated by Django 5.0.3 on 2024-10-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell_that_sheet", "0008_allegroauthtoken_delete_allegrotoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionset",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
