# Generated by Django 5.0.3 on 2024-10-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell_that_sheet", "0010_auction_created_at_auctionset_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddInventoryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddInventoryProductResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="auction",
            name="amount",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="auctionset",
            name="owner",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
